[package]
authors = ["Olly Swanson"]
name = "mars_rover_challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8"
clap = { version = "3.2", features = ["derive"] }
